[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = { version = "0.8" }
wasm-bindgen = "0.2.82"
web-sys = { version = "0.3", features = ["Document", "HtmlCanvasElement", "Window"] }
console_error_panic_hook = { version = "0.1", optional = true }
bevy_rapier3d = { git = "https://github.com/dimforge/bevy_rapier", features = [ "simd-stable", "debug-render" ] }

[features]
default = ["console_error_panic_hook"]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
opt-level = "z"
